# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  deploy-storybook-trivia-jam:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npx nx run trivia-jam:build-storybook
      - name: Deploy Storybook
        run: npx nx run trivia-jam:deploy-storybook

  deploy-storybook-components:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npx nx run components:build-storybook
      - name: Deploy Storybook
        run: npx nx run components:deploy-storybook
