name: Deploy Migrations to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - run: npm ci

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: |
          npx nx run database:link --project-ref $PRODUCTION_PROJECT_ID --password $PRODUCTION_DB_PASSWORD
          npx nx run database:push
